'use client';
import {useEffect,useState} from 'react';
import {pendingReports, queueReport, removeQueuedReport} from './offline-queue';
const api=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8001';
type Incident={id:string;public_reference:string;category:string;location_name?:string;risk_level:string;confidence:number;verification_status:string;ai_summary:string};
export default function Home(){
 const [token,setToken]=useState(''),[incidents,setIncidents]=useState<Incident[]>([]),[text,setText]=useState(''),[location,setLocation]=useState('Kibera'),[notice,setNotice]=useState('');
 const headers=()=>({Authorization:'Bearer '+token,'Content-Type':'application/json'});
 async function load(){if(!token)return;const r=await fetch(api+'/api/v1/incidents',{headers:headers()});if(r.ok)setIncidents(await r.json())}
 async function syncQueue(){if(!navigator.onLine)return;for(const item of await pendingReports()){try{const r=await fetch(api+'/api/v1/reports/text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});if(r.ok)await removeQueuedReport(item.id)}catch{/* retain for retry */}}load()}
 useEffect(()=>{load();syncQueue();addEventListener('online',syncQueue);return()=>removeEventListener('online',syncQueue)},[token]);
 async function login(){const r=await fetch(api+'/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'responder@voicerada.local',password:'change-me'})}),d=await r.json();if(d.access_token){setToken(d.access_token);setNotice('Responder session active.')}else setNotice('Login failed: check .env credentials.')}
 async function submit(e:React.FormEvent){e.preventDefault();const body={text,location_name:location,source_type:'PWA' as const};try{if(!navigator.onLine)throw Error();const r=await fetch(api+'/api/v1/reports/text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error();const d=await r.json();setNotice(d.status==='duplicate'?'This report was already received.':'Report received and triaged as an unverified observation.')}catch{await queueReport(body);setNotice('You are offline. This report is stored locally on this device and will retry when online.')}setText('');load()}
 async function verify(id:string){await fetch(api+'/api/v1/incidents/'+id+'/verification',{method:'PATCH',headers:headers(),body:JSON.stringify({status:'VERIFIED',notes:'Verified during demo review.'})});load()}
 return <main><header><div><b>VoiceRada</b><small>Community early warning · Kenya</small></div><button onClick={login}>{token?'Responder active':'Demo responder login'}</button></header><section className="intro"><p>Operational dashboard</p><h1>Reports need review, not assumptions.</h1><span>Automated triage helps prioritize unverified observations. It is not an official emergency classification.</span></section><div className="grid"><section className="card report"><h2>Submit a community report</h2><form onSubmit={submit}><label>What happened?<textarea required value={text} onChange={e=>setText(e.target.value)} placeholder="Maji imeingia kwa nyumba kadhaa karibu na mto..."/></label><label>Location (optional)<input value={location} onChange={e=>setLocation(e.target.value)}/></label><button>Send report</button></form><p className="notice">{notice}</p></section><section className="card map"><h2>Incident map</h2><div className="mapbox"><span>KENYA · DEMO MAP</span>{incidents.map((i,n)=><i key={i.id} style={{left:(20+n*17)%78+'%',top:(25+n*13)%58+'%'}} title={i.location_name}/>)}</div><small>Mapbox markers are available when configured; this local view never sends location to a third party.</small></section></div><section className="card feed"><h2>Live incident feed</h2>{!token?<p>Log in with the demo responder account to view protected incident data.</p>:incidents.length===0?<p>No reports yet. Submit a fictional report above.</p>:incidents.map(i=><article key={i.id}><div><strong>{i.public_reference}</strong><span className={'pill '+i.risk_level}>{i.risk_level}</span><span className="status">{i.verification_status}</span><h3>{i.category.replace('_',' ')}</h3><p>{i.ai_summary}</p><small>{i.location_name||'Location not resolved'} · confidence {Math.round(i.confidence*100)}% · AI-extracted information</small></div>{i.verification_status==='UNVERIFIED'&&<button onClick={()=>verify(i.id)}>Mark verified</button>}</article>)}</section></main>
}
